---
title: "허현_HW1"
author: "Hyun"
date: "2018년 8월 14일"
output: html_document
mainfont: NanumGothic
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Excercise 3

```{r include = FALSE}
library(Hmisc)
library(mdsr)
library(babynames)
library(dplyr)
```


get data
```{r}
BabynamesDist <- make_babynames_dist()
head(BabynamesDist, 2)
```

men names with summarized age information
```{r}
anti_names <- BabynamesDist %>%
  filter(sex == "M") %>%
  group_by(name) %>%
  summarise(est_num_alive=sum(est_alive_today)) %>%
  filter(est_num_alive==0)%>%
  select(name)

BabynamesDist %>%
  anti_join(anti_names, by="name") %>%
  filter(sex == 'M') %>%
  group_by(name) %>%
  summarise(
    N = n(),
    est_num_alive = sum(est_alive_today),
    q1_age = wtd.quantile(age_today, est_alive_today, probs = 0.25),
    median_age = wtd.quantile(age_today, est_alive_today, probs = 0.5),
    q3_age = wtd.quantile(age_today, est_alive_today, probs = 0.75)
  ) %>%
  arrange(desc(median_age)) %>%
  head(20)
```

```{r}

```